Repository wilhelm-lab/koina, pull requests merged in 2024-10, with the labels that each got.

#114 Update UI
  models/Deeplc/Deeplc_hela_hf/notes.yaml
  models/Deeplc/IM2Deep/notes.yaml
  web/assets/img/msaid-logo.png
  web/assets/img/msaid-logo.webp
  web/pages/index.vue
Labels: docs

#121 Fix ms2pip version.
  Dockerfile
Labels: docs

#123 Add Chronologer.
  clients/python/test/Chronologer/__init__.py
  clients/python/test/Chronologer/arr-Chronologer_RT-peptide_sequences.npy
  clients/python/test/Chronologer/arr-Chronologer_RT-rt.npy
  clients/python/test/Chronologer/test_Chronologer_RT.py
  models/Chronologer/Chronologer_Preprocess/1/model.py
  models/Chronologer/Chronologer_Preprocess/1/sequence_conversion.py
  models/Chronologer/Chronologer_Preprocess/config.pbtxt
  models/Chronologer/Chronologer_RT/1/.gitkeep
  models/Chronologer/Chronologer_RT/1/model.py
  models/Chronologer/Chronologer_RT/config.pbtxt
  models/Chronologer/Chronologer_RT/notes.yaml
  models/Chronologer/Chronologer_RT_core/1/.zenodo
  models/Chronologer/Chronologer_RT_core/config.pbtxt
  models/Chronologer/Chronologer_RT_sb/1/.gitkeep
  models/Chronologer/Chronologer_RT_sb/config.pbtxt
Labels: patch

#124 Feature/trigger cd
  README.md
  clients/python/pyproject.toml
Labels: patch, python-client

#127 New testing scheme
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-annotation.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-collision_energies.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-intensities.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-mz.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-peptide_sequences_1.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-peptide_sequences_2.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2-precursor_charges.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2_core-collision_energy_in.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2_core-out_1.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2_core-peptides_in1.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2_core-peptides_in2.npy
  clients/python/test/Prosit/arr-Prosit_2024_intensity_XL_NMS2_core-precursor_charge_in.npy
  clients/python/test/Prosit/test_Prosit_2024_intensity_XL_NMS2.py
  clients/python/test/Prosit/test_Prosit_2024_intensity_XL_NMS2_core.py
  models/Prosit/Prosit_2024_intensity_XL_NMS2/1/.donotdelete
  models/Prosit/Prosit_2024_intensity_XL_NMS2/config.pbtxt
  models/Prosit/Prosit_2024_intensity_XL_NMS2/notes.yaml
  models/Prosit/Prosit_2024_intensity_XL_NMS2_core/1/.zenodo
  models/Prosit/Prosit_2024_intensity_XL_NMS2_core/config.pbtxt
  models/Prosit/XL_Prosit_NMS2_2024_intensity_postprocess/1/constants.py
  models/Prosit/XL_Prosit_NMS2_2024_intensity_postprocess/1/model.py
  models/Prosit/XL_Prosit_NMS2_2024_intensity_postprocess/1/postprocess.py
  models/Prosit/XL_Prosit_NMS2_2024_intensity_postprocess/config.pbtxt
  models/Prosit/XL_Prosit_NMS2_Helper_annotation/1/model.py
  models/Prosit/XL_Prosit_NMS2_Helper_annotation/config.pbtxt
  models/Prosit/XL_Prosit_Preprocess_peptide_NMS2/1/model.py
  models/Prosit/XL_Prosit_Preprocess_peptide_NMS2/1/sequence_conversion.py
  models/Prosit/XL_Prosit_Preprocess_peptide_NMS2/config.pbtxt
Labels: patch

#128 Added 3dmolms models.
  Dockerfile
  clients/python/test/molms/__init__.py
  clients/python/test/molms/arr-3dmolms_orbitrap-collision_energies.npy
  clients/python/test/molms/arr-3dmolms_orbitrap-intensities.npy
  clients/python/test/molms/arr-3dmolms_orbitrap-mz.npy
  clients/python/test/molms/arr-3dmolms_orbitrap-precursor_types.npy
  clients/python/test/molms/arr-3dmolms_orbitrap-smiles.npy
  clients/python/test/molms/arr-3dmolms_orbitrap_core-3dmolms_out.npy
  clients/python/test/molms/arr-3dmolms_orbitrap_core-env.npy
  clients/python/test/molms/arr-3dmolms_orbitrap_core-idx_base.npy
  clients/python/test/molms/arr-3dmolms_orbitrap_core-x.npy
  clients/python/test/molms/arr-3dmolms_qtof-collision_energies.npy
  clients/python/test/molms/arr-3dmolms_qtof-intensities.npy
  clients/python/test/molms/arr-3dmolms_qtof-mz.npy
  clients/python/test/molms/arr-3dmolms_qtof-precursor_types.npy
  clients/python/test/molms/arr-3dmolms_qtof-smiles.npy
  clients/python/test/molms/arr-3dmolms_qtof_core-3dmolms_out.npy
  clients/python/test/molms/arr-3dmolms_qtof_core-env.npy
  clients/python/test/molms/arr-3dmolms_qtof_core-idx_base.npy
  clients/python/test/molms/arr-3dmolms_qtof_core-x.npy
  clients/python/test/molms/test_3dmolms_orbitrap.py
  clients/python/test/molms/test_3dmolms_orbitrap_core.py
  clients/python/test/molms/test_3dmolms_qtof.py
  clients/python/test/molms/test_3dmolms_qtof_core.py
  models/3dmolms/3dmolms_orbitrap/1/.gitkeep
  models/3dmolms/3dmolms_orbitrap/config.pbtxt
  models/3dmolms/3dmolms_orbitrap/notes.yaml
  models/3dmolms/3dmolms_orbitrap_core/1/.zenodo
  models/3dmolms/3dmolms_orbitrap_core/config.pbtxt
  models/3dmolms/3dmolms_postprocess/1/model.py
  models/3dmolms/3dmolms_postprocess/config.pbtxt
  models/3dmolms/3dmolms_preprocess/1/3dmolms_config.json
  models/3dmolms/3dmolms_preprocess/1/model.py
  models/3dmolms/3dmolms_preprocess/config.pbtxt
  models/3dmolms/3dmolms_qtof/1/.gitkeep
  models/3dmolms/3dmolms_qtof/config.pbtxt
  models/3dmolms/3dmolms_qtof/notes.yaml
  models/3dmolms/3dmolms_qtof_core/1/.zenodo
  models/3dmolms/3dmolms_qtof_core/config.pbtxt
Labels: patch

#129 Add MS2PIP model descriptions
  models/ms2pip/ms2pip_CID_TMT/notes.yaml
  models/ms2pip/ms2pip_HCD2021/notes.yaml
  models/ms2pip/ms2pip_Immuno_HCD/notes.yaml
  models/ms2pip/ms2pip_TTOF5600/notes.yaml
  models/ms2pip/ms2pip_iTRAQphospho/notes.yaml
  models/ms2pip/ms2pip_timsTOF2023/notes.yaml
  models/ms2pip/ms2pip_timsTOF2024/notes.yaml
Labels: patch

#130 Fix CI
  .github/workflows/release_docker.yml
Labels: patch
