Repository wilhelm-lab/koina, pull requests merged in 2024-08, with the labels that each got.

#105 Fix/startup speed, update UI & fix linting
  .pylintrc
  Dockerfile
  entrypoint.sh
  models/AlphaPept/AlphaPeptDeep_ccs_generic/1/model.py
  models/AlphaPept/AlphaPeptDeep_ccs_generic/config.pbtxt
  models/AlphaPept/AlphaPeptDeep_ccs_generic/notes.yaml
  models/AlphaPept/AlphaPeptDeep_ms2_generic/1/model.py
  models/AlphaPept/AlphaPeptDeep_ms2_generic/config.pbtxt
  models/AlphaPept/AlphaPeptDeep_ms2_generic/notes.yaml
  models/AlphaPept/AlphaPeptDeep_rt_generic/1/model.py
  models/AlphaPept/AlphaPeptDeep_rt_generic/config.pbtxt
  models/AlphaPept/AlphaPeptDeep_rt_generic/notes.yaml
  models/Deeplc/Deeplc_hela_hf/notes.yaml
  models/Deeplc/IM2Deep/notes.yaml
  models/Prosit/Prosit_2019_intensity/notes.yaml
  models/Prosit/Prosit_2019_irt/notes.yaml
  models/Prosit/Prosit_2020_intensity_CID/notes.yaml
  models/Prosit/Prosit_2020_intensity_HCD/notes.yaml
  models/Prosit/Prosit_2020_intensity_TMT/notes.yaml
  models/Prosit/Prosit_2020_irt_TMT/notes.yaml
  models/Prosit/Prosit_2023_intensity_XL_CMS2/notes.yaml
  models/Prosit/Prosit_2023_intensity_XL_CMS3/notes.yaml
  models/Prosit/Prosit_2023_intensity_timsTOF/notes.yaml
  models/Prosit/Prosit_Preprocess_peptide/1/model.py
  models/Prosit/Prosit_Preprocess_peptide/1/sequence_conversion.py
  models/Prosit/XL_Prosit_Preprocess_peptide_CMS3/1/model.py
  models/Prosit/XL_Prosit_Preprocess_peptide_CMS3/1/sequence_conversion.py
  models/ms2pip/ms2pip_CID_TMT/notes.yaml
  models/ms2pip/ms2pip_HCD2021/notes.yaml
  models/ms2pip/ms2pip_Immuno_HCD/notes.yaml
  models/ms2pip/ms2pip_TTOF5600/notes.yaml
  models/ms2pip/ms2pip_iTRAQphospho/notes.yaml
  models/ms2pip/ms2pip_preprocess/1/tobi.py
  models/ms2pip/ms2pip_timsTOF2023/notes.yaml
  models/ms2pip/ms2pip_timsTOF2024/notes.yaml
  models/start.py
  web/assets/css/tailwind.css
  web/components/partials/TheHero.vue
  web/openapi/openapi_gen.py
  web/openapi/templates/openapi.yml
  web/package-lock.json
  web/pages/index.vue
Labels: patch

#107 Tolerate Errors during prerendering.
  web/nuxt.config.ts
Labels: docs

#109 Changed the name usprocess to UniSpec
  clients/python/test/UniSpec/arr-UniSpec-annotation.npy
  clients/python/test/UniSpec/arr-UniSpec-collision_energies.npy
  clients/python/test/UniSpec/arr-UniSpec-instrument_types.npy
  clients/python/test/UniSpec/arr-UniSpec-intensities.npy
  clients/python/test/UniSpec/arr-UniSpec-mz.npy
  clients/python/test/UniSpec/arr-UniSpec-peptide_sequences.npy
  clients/python/test/UniSpec/arr-UniSpec-precursor_charges.npy
  clients/python/test/UniSpec/test_UniSpec.py
  models/UniSpec/UniSpec/1/model.py
  models/UniSpec/UniSpec/config.pbtxt
  models/UniSpec/UniSpec/dictionary.txt
  models/UniSpec/UniSpec/masses.txt
  models/UniSpec/UniSpec/modifications.txt
  models/UniSpec/UniSpec/notes.yaml
Labels: patch

#112 Update UniSpec documentation
  models/UniSpec/UniSpec/notes.yaml
Labels: docs

#108 fixed race condition in retry mechanism
  clients/python/koinapy/grpc.py
  clients/python/pyproject.toml
Labels: python-client

#113 Fixed control statements in NCE2eV subroutine. Now all instrument
  models/UniSpec/UniSpec/1/model.py
Labels: patch
